version: '3.8'

services:
  keycloak:
    container_name: keycloak-dev
    image: quay.io/keycloak/keycloak:25.0.1
    command:
      - start-dev
      - --import-realm
    ports:
      - "8180:8080"
    volumes:
      - ./keycloak/:/opt/keycloak/data/import/
    environment:
      # Простые учетные данные для теста
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      
      # HTTP настройки
      KC_HTTP_PORT: 8080
      KC_HOSTNAME_URL: http://localhost:8180
      KC_HOSTNAME_ADMIN_URL: http://localhost:8180
      KC_HTTP_ENABLED: true
      KC_HEALTH_ENABLED: true
      KC_METRICS_ENABLED: true
      
      # Логирование
      KC_LOG_LEVEL: INFO
    healthcheck:
      test: ["CMD-SHELL", "exec 3<>/dev/tcp/127.0.0.1/8080;echo -e 'GET /health/ready HTTP/1.1\r\nhost: http://localhost\r\nConnection: close\r\n\r\n' >&3;grep -q 'HTTP/1.1 200' || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s